name: Publish Templates

on:
  push:
    branches:
      - main

env:
  FORCE_COLOR: 3

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: read

jobs:
  publish_template:
    name: Publish Template
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: internal
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Set up pnpm
        uses: step-security/action-setup@3d419c73e38e670dbffe349ffff26dd13c164640 # v4.2.0
        with:
          version: 9.13.0

      - name: Set up Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 24
          cache: pnpm

      - name: Install pnpm Dependencies
        run: pnpm i --frozen-lockfile --ignore-scripts

      - name: Get changed files
        id: changed-files
        run: |
          changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | tr '\n' ' ')
          echo "all_changed_files=${changed_files}" >> $GITHUB_OUTPUT

      - name: Publish template
        run: pnpm update-templates "${{ steps.changed-files.outputs.all_changed_files }}"
        env:
          CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
          CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
          CONTENTFUL_ENVIRONMENT: ${{ secrets.CONTENTFUL_ENVIRONMENT }}
          CONTENTFUL_CONTENT_TYPE: ${{ secrets.CONTENTFUL_CONTENT_TYPE }}
