name: Release @vercel/examples-ui

on:
  push:
    branches:
      - main

env:
  FORCE_COLOR: 3
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: vercel

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: read

jobs:
  release:
    permissions:
      contents: write  # for changesets/action to push to the repo
      pull-requests: write  # for changesets/action to create PRs
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Set up pnpm
        uses: step-security/action-setup@3d419c73e38e670dbffe349ffff26dd13c164640 # v4.2.0

      - name: Set up Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 20
          cache: pnpm

      - name: Install Dependencies
        run: pnpm i --frozen-lockfile --ignore-scripts
        working-directory: internal

      - name: Create Release PR or Publish Packages
        # Last known version working with cwd
        # https://github.com/changesets/action/issues/501
        uses: step-security/changeset-action@c3cee0943e9b8be3a72f62588e00dd7c107e101e # v1.6.0
        with:
          cwd: internal
          # Builds the package and executes `changeset publish`
          publish: pnpm release
          # Alias to `changeset version` script in package.json
          version: pnpm version-packages
          commit: 'chore: update package versions'
          title: 'chore: update package versions'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN_ELEVATED }}
